import { StaticScanResult, DynamicScanResult, CryptoFinding } from '../types/scan';

export const DEMO_BANK_APP_RESULT: StaticScanResult = {
  scan_id: "scan-bank-demo-001",
  target_name: "Quantum-Vulnerable Core Banking Backend (Python)",
  total_files_scanned: 14,
  total_crypto_assets: 6,
  quantum_readiness_score: 28,
  hndl_exposure_rating: "CRITICAL (Immediate Harvest Now, Decrypt Later Threat)",
  shor_broken_count: 2,
  grover_degraded_count: 1,
  deprecated_classical_count: 3,
  quantum_safe_count: 0,
  scanned_languages: ["Python", "YAML", "Docker"],
  scan_logs: [
    "[00:00.12] ▶ Initializing Aegis-Q AST & Static Cryptographic Scanner...",
    "[00:00.25] ▶ Found 14 source files in repository...",
    "[00:00.41] 🔴 Detected Shor-vulnerable RSA-2048 at auth_service.py:12",
    "[00:00.58] ⚠️ Detected Deprecated MD5 at auth_service.py:18",
    "[00:00.72] ⚠️ Detected Deprecated SHA-1 at audit_ledger.py:24",
    "[00:00.89] ⚠️ Detected Deprecated AES-ECB at payment_vault.py:31",
    "[00:01.05] ⚠️ Detected Deprecated DES at legacy_cards.py:15",
    "[00:01.21] 🔴 Detected Shor-vulnerable RSA-OAEP at session_manager.py:42",
    "[00:01.35] ▶ Scan complete. Discovered 6 cryptographic assets.",
    "[00:01.38] ▶ Quantum Readiness Index: 28% | Primary Threat: Shor Factorization of RSA-2048"
  ],
  findings: [
    {
      id: "find-bank-01",
      algorithm: "RSA-2048",
      primitive: "Asymmetric Encryption",
      key_size: 2048,
      risk_level: "CRITICAL_SHOR",
      risk_reason: "Vulnerable to complete factorization via Shor's Algorithm running on a Cryptanalytically Relevant Quantum Computer (CRQC).",
      nist_replacement: "ML-KEM-768 (NIST FIPS 203)",
      nist_standard: "ML-KEM",
      file_path: "app/services/auth_service.py",
      line_number: 12,
      code_snippet: "self.rsa_keypair = RSA.generate(2048)\nself.public_key = self.rsa_keypair.publickey().export_key()\nself.private_key = self.rsa_keypair.export_key()",
      framework_or_library: "PyCryptodome RSA",
      confidence: 0.99,
      oid: "1.2.840.113549.1.1.1",
      quantum_security_level: 0
    },
    {
      id: "find-bank-02",
      algorithm: "RSA-2048",
      primitive: "Key Exchange",
      key_size: 2048,
      risk_level: "CRITICAL_SHOR",
      risk_reason: "Asymmetric session token key transport vulnerable to Harvest Now, Decrypt Later (HNDL) data collection.",
      nist_replacement: "ML-KEM-768 (NIST FIPS 203) / Kyber",
      nist_standard: "ML-KEM",
      file_path: "app/services/session_manager.py",
      line_number: 42,
      code_snippet: "cipher = PKCS1_OAEP.new(RSA.import_key(self.public_key))\nreturn cipher.encrypt(token)",
      framework_or_library: "Crypto.Cipher.PKCS1_OAEP",
      confidence: 0.98,
      oid: "1.2.840.113549.1.1.7",
      quantum_security_level: 0
    },
    {
      id: "find-bank-03",
      algorithm: "AES-ECB",
      primitive: "Symmetric Encryption",
      mode_of_operation: "ECB",
      risk_level: "DEPRECATED_CLASSICAL",
      risk_reason: "Electronic Codebook (ECB) mode lacks cryptographic diffusion. Identical plaintext blocks encrypt to identical ciphertext blocks.",
      nist_replacement: "AES-256-GCM (NIST FIPS 197)",
      nist_standard: "AES-256",
      file_path: "app/services/payment_vault.py",
      line_number: 31,
      code_snippet: "cipher = AES.new(symmetric_key[:16], AES.MODE_ECB)\nreturn cipher.encrypt(raw_data)",
      framework_or_library: "PyCryptodome AES",
      confidence: 0.97,
      oid: "2.16.840.1.101.3.4.1.1",
      quantum_security_level: 0
    },
    {
      id: "find-bank-04",
      algorithm: "DES",
      primitive: "Symmetric Encryption",
      key_size: 56,
      risk_level: "DEPRECATED_CLASSICAL",
      risk_reason: "Obsolete 56-bit key length cracked classically in hours. Vulnerable to Grover brute-force in seconds.",
      nist_replacement: "AES-256-GCM (NIST FIPS 197)",
      nist_standard: "AES-256",
      file_path: "app/services/legacy_cards.py",
      line_number: 15,
      code_snippet: "des_cipher = DES.new(b'BANK8KEY', DES.MODE_ECB)\nreturn des_cipher.encrypt(track2_data)",
      framework_or_library: "PyCryptodome DES",
      confidence: 1.0,
      oid: "1.3.14.3.2.7",
      quantum_security_level: 0
    },
    {
      id: "find-bank-05",
      algorithm: "MD5",
      primitive: "Hash Function",
      risk_level: "DEPRECATED_CLASSICAL",
      risk_reason: "Collision resistance completely broken (CVE-2004-2761). Trivially spoofable hash digests.",
      nist_replacement: "SHA3-512 / SHA-256 (NIST FIPS 202)",
      nist_standard: "SHA3-512",
      file_path: "app/services/auth_service.py",
      line_number: 18,
      code_snippet: "return hashlib.md5(pin.encode('utf-8')).hexdigest()",
      framework_or_library: "Python hashlib",
      confidence: 0.99,
      oid: "1.2.840.113549.2.5",
      quantum_security_level: 0
    },
    {
      id: "find-bank-06",
      algorithm: "SHA-1",
      primitive: "Hash Function",
      risk_level: "DEPRECATED_CLASSICAL",
      risk_reason: "Practical collision attacks demonstrated (SHAttered attack). Deprecated by NIST.",
      nist_replacement: "SHA3-512 (NIST FIPS 202)",
      nist_standard: "SHA3-512",
      file_path: "app/services/audit_ledger.py",
      line_number: 24,
      code_snippet: "return hashlib.sha1(transaction_data).hexdigest()",
      framework_or_library: "Python hashlib",
      confidence: 0.99,
      oid: "1.3.14.3.2.26",
      quantum_security_level: 0
    }
  ]
};

export const DEMO_NODE_CRYPTO_RESULT: StaticScanResult = {
  scan_id: "scan-node-demo-002",
  target_name: "Legacy E-Commerce Authentication (Node.js)",
  total_files_scanned: 8,
  total_crypto_assets: 4,
  quantum_readiness_score: 34,
  hndl_exposure_rating: "HIGH (RSA-2048 & 3DES Detected)",
  shor_broken_count: 1,
  grover_degraded_count: 1,
  deprecated_classical_count: 2,
  quantum_safe_count: 0,
  scanned_languages: ["JavaScript", "JSON"],
  scan_logs: [
    "[00:00.10] ▶ Scanning Node.js workspace...",
    "[00:00.32] 🔴 Detected RSA-2048 KeyPair in auth.js:6",
    "[00:00.54] ⚠️ Detected MD5 hash in password.js:14",
    "[00:00.70] ⚠️ Detected 3DES in payments.js:28",
    "[00:00.86] 🟡 Detected AES-128-ECB in session.js:35",
    "[00:01.02] ▶ Completed scan. 4 findings discovered."
  ],
  findings: [
    {
      id: "find-node-01",
      algorithm: "RSA-2048",
      primitive: "Asymmetric Encryption",
      key_size: 2048,
      risk_level: "CRITICAL_SHOR",
      risk_reason: "RSA public key operations broken by Shor's quantum algorithm.",
      nist_replacement: "ML-KEM-768 (NIST FIPS 203)",
      nist_standard: "ML-KEM",
      file_path: "src/auth.js",
      line_number: 6,
      code_snippet: "const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', { modulusLength: 2048 });",
      framework_or_library: "Node.js crypto",
      confidence: 0.99,
      oid: "1.2.840.113549.1.1.1",
      quantum_security_level: 0
    },
    {
      id: "find-node-02",
      algorithm: "MD5",
      primitive: "Hash Function",
      risk_level: "DEPRECATED_CLASSICAL",
      risk_reason: "MD5 hash collisions allow signature forgery.",
      nist_replacement: "SHA-256 / SHA3-512 (NIST FIPS 202)",
      nist_standard: "SHA3-512",
      file_path: "src/password.js",
      line_number: 14,
      code_snippet: "return crypto.createHash('md5').update(password).digest('hex');",
      framework_or_library: "Node.js crypto",
      confidence: 0.98,
      oid: "1.2.840.113549.2.5",
      quantum_security_level: 0
    }
  ]
};

export const DEMO_SECURE_REFERENCE_RESULT: StaticScanResult = {
  scan_id: "scan-secure-demo-003",
  target_name: "Post-Quantum Secure Reference Architecture",
  total_files_scanned: 16,
  total_crypto_assets: 4,
  quantum_readiness_score: 98,
  hndl_exposure_rating: "QUANTUM-RESISTANT (NIST Standards Active)",
  shor_broken_count: 0,
  grover_degraded_count: 0,
  deprecated_classical_count: 0,
  quantum_safe_count: 4,
  scanned_languages: ["Python", "Rust", "C++"],
  scan_logs: [
    "[00:00.12] ▶ Scanning Post-Quantum Reference Stack...",
    "[00:00.28] ✅ Verified NIST FIPS 203 ML-KEM-768 key encapsulation",
    "[00:00.44] ✅ Verified NIST FIPS 204 ML-DSA-65 digital signatures",
    "[00:00.61] ✅ Verified AES-256-GCM authenticated encryption",
    "[00:00.75] ✅ Verified NIST FIPS 202 SHA3-512 hash digests",
    "[00:00.91] ▶ Quantum Readiness Index: 98% (Fully Fortified)"
  ],
  findings: [
    {
      id: "find-sec-01",
      algorithm: "ML-KEM-768",
      primitive: "Key Exchange",
      risk_level: "QUANTUM_SAFE",
      risk_reason: "NIST FIPS 203 standardized module-lattice key encapsulation mechanism.",
      nist_replacement: "Active NIST PQC Standard",
      nist_standard: "ML-KEM",
      file_path: "src/pqc_transport.py",
      line_number: 18,
      code_snippet: "with oqs.KeyEncapsulation('ML-KEM-768') as kem:\n    ciphertext, shared_secret = kem.encap_secret(client_pub)",
      framework_or_library: "liboqs / Open Quantum Safe",
      confidence: 1.0,
      oid: "2.16.840.1.101.3.4.4.2",
      quantum_security_level: 5
    },
    {
      id: "find-sec-02",
      algorithm: "ML-DSA-65",
      primitive: "Digital Signature",
      risk_level: "QUANTUM_SAFE",
      risk_reason: "NIST FIPS 204 standardized lattice-based digital signature.",
      nist_replacement: "Active NIST PQC Standard",
      nist_standard: "ML-DSA",
      file_path: "src/pqc_signatures.py",
      line_number: 30,
      code_snippet: "with oqs.Signature('ML-DSA-65') as signer:\n    signature = signer.sign(message)",
      framework_or_library: "liboqs / Open Quantum Safe",
      confidence: 1.0,
      oid: "2.16.840.1.101.3.4.3.18",
      quantum_security_level: 5
    }
  ]
};

export const DEMO_DYNAMIC_TLS_RESULT: DynamicScanResult = {
  target_host: "secure.bank-portal.com",
  target_port: 443,
  resolved_ip: "104.21.48.112",
  tls_version: "TLSv1.3",
  cipher_info: {
    cipher_suite: "TLS_AES_128_GCM_SHA256",
    protocol_version: "TLSv1.3",
    key_exchange: "ECDHE X25519 (Shor Broken)",
    encryption: "AES-128-GCM (Grover Degraded)",
    mac_or_hash: "SHA-256",
    quantum_risk: "CRITICAL_SHOR",
    is_pqc_hybrid: false
  },
  certificate: {
    subject: { CN: "secure.bank-portal.com", O: "Global Banking Corp" },
    issuer: { O: "DigiCert Global Root G2", CN: "DigiCert TLS RSA SHA256 2020 CA1" },
    valid_from: "2024-01-15T00:00:00Z",
    valid_to: "2025-01-15T23:59:59Z",
    days_remaining: 142,
    signature_algorithm: "sha256WithRSAEncryption",
    public_key_type: "RSA",
    public_key_bits: 2048,
    subject_alt_names: ["secure.bank-portal.com", "api.bank-portal.com", "auth.bank-portal.com"],
    serial_number: "0x3a4f89d102e7b99c",
    is_quantum_vulnerable: true,
    quantum_risk: "CRITICAL_SHOR"
  },
  supported_protocols: ["TLSv1.3", "TLSv1.2"],
  supported_ciphers: [
    "TLS_AES_128_GCM_SHA256",
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
    "ECDHE-RSA-AES128-GCM-SHA256"
  ],
  handshake_steps: [
    { step_number: 1, name: "ClientHello", status: "completed", detail: "Proposing TLS 1.3 / 1.2 client suites", timestamp_ms: 12.4 },
    { step_number: 2, name: "ServerHello", status: "completed", detail: "Server selected TLS 1.3 with TLS_AES_128_GCM_SHA256", timestamp_ms: 38.2 },
    { step_number: 3, name: "Certificate", status: "completed", detail: "Subject: CN=secure.bank-portal.com | Sig: RSA-2048", timestamp_ms: 64.7 },
    { step_number: 4, name: "Key Exchange", status: "completed", detail: "Key Exchange: ECDHE X25519 (Shor Broken)", timestamp_ms: 89.1 },
    { step_number: 5, name: "Finished", status: "completed", detail: "TLS Handshake finished. Cryptographic evaluation complete.", timestamp_ms: 104.5 }
  ],
  quantum_readiness_score: 35,
  hndl_exposure_rating: "CRITICAL (Harvest Now, Decrypt Later Threat Active)",
  shor_vulnerable_count: 2,
  grover_vulnerable_count: 1,
  findings: [
    {
      id: "tls-find-01",
      algorithm: "ECDHE-X25519",
      primitive: "Key Exchange",
      risk_level: "CRITICAL_SHOR",
      risk_reason: "Elliptic-curve Diffie-Hellman key exchange is broken by Shor's algorithm, allowing retroactive session decryption.",
      nist_replacement: "ML-KEM-768 (NIST FIPS 203) / X25519MLKEM768 Hybrid",
      nist_standard: "ML-KEM",
      file_path: "https://secure.bank-portal.com:443 [Key Exchange]",
      code_snippet: "Cipher Suite: TLS_AES_128_GCM_SHA256\nKey Exchange: ECDHE-X25519\nProtocol: TLSv1.3",
      framework_or_library: "TLS 1.3 Transport Layer",
      confidence: 1.0,
      oid: "1.3.132.1.12",
      quantum_security_level: 0
    },
    {
      id: "tls-find-02",
      algorithm: "RSA-2048",
      primitive: "Digital Signature",
      key_size: 2048,
      risk_level: "CRITICAL_SHOR",
      risk_reason: "Server certificate signed with RSA-2048; susceptible to quantum forgery once CRQC machines emerge.",
      nist_replacement: "ML-DSA-65 (NIST FIPS 204)",
      nist_standard: "ML-DSA",
      file_path: "https://secure.bank-portal.com [X.509 Certificate]",
      code_snippet: "Issuer: DigiCert TLS RSA SHA256 2020 CA1\nSubject: CN=secure.bank-portal.com\nPublic Key: RSA 2048-bit",
      framework_or_library: "X.509 PKI Certificate",
      confidence: 1.0,
      oid: "1.2.840.113549.1.1.1",
      quantum_security_level: 0
    },
    {
      id: "tls-find-03",
      algorithm: "AES-128-GCM",
      primitive: "Symmetric Encryption",
      key_size: 128,
      risk_level: "MEDIUM_GROVER",
      risk_reason: "Grover's algorithm reduces effective brute-force security to 64 bits. Recommend upgrading to 256 bits.",
      nist_replacement: "AES-256-GCM (NIST FIPS 197)",
      nist_standard: "AES-256",
      file_path: "https://secure.bank-portal.com [Record Layer]",
      code_snippet: "Encryption: AES-128-GCM\nMode: Galois/Counter Mode\nTag: 128-bit AEAD",
      framework_or_library: "TLS Record Protocol",
      confidence: 1.0,
      oid: "2.16.840.1.101.3.4.1.6",
      quantum_security_level: 1
    }
  ]
};
