import React, { useState } from 'react';
import { X, Download, FileCode, FileSpreadsheet, FileText, CheckCircle2, Loader2 } from 'lucide-react';
import { CryptoFinding } from '../../types/scan';
import { exportCbomJson } from '../../services/api';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  targetName: string;
  findings: CryptoFinding[];
  score: number;
  onShowToast: (type: 'success' | 'info' | 'warning', title: string, msg: string) => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  targetName,
  findings,
  score,
  onShowToast,
}) => {
  const [selectedFormat, setSelectedFormat] = useState<'cyclonedx' | 'pdf' | 'csv' | 'markdown'>('cyclonedx');
  const [isExporting, setIsExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState(0);

  if (!isOpen) return null;

  const handleDownload = async () => {
    setIsExporting(true);
    setExportProgress(25);

    setTimeout(async () => {
      setExportProgress(65);

      if (selectedFormat === 'cyclonedx') {
        const cbom = await exportCbomJson(targetName, findings, 'static');
        const blob = new Blob([JSON.stringify(cbom, null, 2)], { type: 'application/json' });
        triggerDownload(blob, `cbom_cyclonedx_${sanitize(targetName)}.json`);
      } else if (selectedFormat === 'csv') {
        const headers = 'Algorithm,Primitive,KeySize,RiskLevel,Location,NIST_Replacement\n';
        const rows = findings.map(f => `"${f.algorithm}","${f.primitive}","${f.key_size || 'N/A'}","${f.risk_level}","${f.file_path || 'Endpoint'}","${f.nist_replacement}"`).join('\n');
        const blob = new Blob([headers + rows], { type: 'text/csv' });
        triggerDownload(blob, `cryptographic_inventory_${sanitize(targetName)}.csv`);
      } else if (selectedFormat === 'markdown') {
        const md = `# Aegis-Q Cryptographic Discovery & Post-Quantum Assessment Report
**Target System:** ${targetName}
**Quantum Readiness Index:** ${score}%
**Date:** ${new Date().toUTCString()}

## Executive Summary
- Total Cryptographic Assets: ${findings.length}
- Shor Vulnerable (Public Key): ${findings.filter(f => f.risk_level.includes('SHOR')).length}
- Grover Degraded (Symmetric): ${findings.filter(f => f.risk_level.includes('GROVER')).length}
- Deprecated Classical (MD5/SHA1/DES): ${findings.filter(f => f.risk_level.includes('DEPRECATED')).length}

## Discovered Cryptographic Inventory (CBOM)
| Algorithm | Primitive | Location | Risk Level | NIST PQC Target |
|---|---|---|---|---|
${findings.map(f => `| **${f.algorithm}** | ${f.primitive} | \`${f.file_path || 'Endpoint'}:${f.line_number || 0}\` | \`${f.risk_level}\` | **${f.nist_replacement}** |`).join('\n')}

---
*Generated by Aegis-Q Quantum-Safe Discovery Engine (SIH26164)*
`;
        const blob = new Blob([md], { type: 'text/markdown' });
        triggerDownload(blob, `aegis_q_audit_report_${sanitize(targetName)}.md`);
      } else {
        // PDF / Print format triggers standard window print dialog with report styling
        window.print();
      }

      setExportProgress(100);
      setTimeout(() => {
        setIsExporting(false);
        onClose();
        onShowToast('success', 'Report Exported', `${selectedFormat.toUpperCase()} document packaged and saved.`);
      }, 500);
    }, 600);
  };

  const sanitize = (str: string) => str.toLowerCase().replace(/[^a-z0-9]/g, '_');

  const triggerDownload = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const formats = [
    {
      id: 'cyclonedx',
      title: 'CycloneDX v1.6 CBOM JSON',
      desc: 'Official OWASP cryptographic bill of materials standard with NIST quantum security tags.',
      icon: <FileCode className="w-5 h-5 text-indigo-400" />
    },
    {
      id: 'markdown',
      title: 'Markdown Compliance Audit Report',
      desc: 'Complete vulnerability breakdown and remediation roadmap formatted for GitHub / GitLab.',
      icon: <FileText className="w-5 h-5 text-purple-400" />
    },
    {
      id: 'csv',
      title: 'CSV Cryptographic Inventory',
      desc: 'Tabular dataset ready for importing into enterprise SIEM, Excel, and security spreadsheets.',
      icon: <FileSpreadsheet className="w-5 h-5 text-emerald-400" />
    },
    {
      id: 'pdf',
      title: 'Executive Print / PDF Summary',
      desc: 'Polished executive security brief suitable for leadership and compliance auditors.',
      icon: <FileText className="w-5 h-5 text-pink-400" />
    }
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-xl animate-fadeIn">
      <div className="glass-panel w-full max-w-lg p-6 relative border border-white/[0.12] shadow-2xl">
        <div className="flex items-center justify-between pb-4 border-b border-white/[0.08]">
          <div className="flex items-center gap-2.5">
            <Download className="w-5 h-5 text-indigo-400" />
            <h3 className="text-lg font-heading font-bold text-white tracking-tight">
              Export Cryptographic Report
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg bg-white/[0.04] text-white/50 hover:text-white transition-all cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Options List */}
        <div className="space-y-2.5 my-6">
          {formats.map((fmt) => (
            <div
              key={fmt.id}
              onClick={() => setSelectedFormat(fmt.id as any)}
              className={`p-3.5 rounded-xl border cursor-pointer transition-all flex items-start gap-3.5 ${
                selectedFormat === fmt.id
                  ? 'bg-indigo-500/[0.08] border-indigo-500/50 shadow-[0_0_20px_rgba(99,102,241,0.15)]'
                  : 'bg-white/[0.02] border-white/[0.06] hover:bg-white/[0.04]'
              }`}
            >
              <div className="p-2 rounded-lg bg-white/[0.03] mt-0.5">
                {fmt.icon}
              </div>
              <div className="flex-1">
                <div className="text-xs font-bold text-white">{fmt.title}</div>
                <div className="text-[11px] text-white/50 font-sans mt-0.5 leading-relaxed">{fmt.desc}</div>
              </div>
              <div
                className={`w-4 h-4 rounded-full border mt-1 flex items-center justify-center ${
                  selectedFormat === fmt.id
                    ? 'border-indigo-400 bg-indigo-500'
                    : 'border-white/20'
                }`}
              >
                {selectedFormat === fmt.id && <div className="w-1.5 h-1.5 rounded-full bg-white" />}
              </div>
            </div>
          ))}
        </div>

        {/* Progress bar if exporting */}
        {isExporting && (
          <div className="mb-4 space-y-1.5 font-mono text-xs text-indigo-300">
            <div className="flex justify-between">
              <span>Packaging cryptographic payload...</span>
              <span>{exportProgress}%</span>
            </div>
            <div className="h-1.5 w-full bg-white/[0.06] rounded-full overflow-hidden">
              <div
                className="h-full bg-indigo-500 transition-all duration-300"
                style={{ width: `${exportProgress}%` }}
              />
            </div>
          </div>
        )}

        {/* Action Button */}
        <button
          onClick={handleDownload}
          disabled={isExporting}
          className="w-full py-3 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs transition-all shadow-[0_0_20px_rgba(99,102,241,0.4)] flex items-center justify-center gap-2 cursor-pointer"
        >
          {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          {isExporting ? 'Generating Document...' : 'Download Report'}
        </button>
      </div>
    </div>
  );
};
